// frontend/src/components/WorkoutRunner.vue
<template>
  <div class="workout-runner bg-[#1e1e2e] h-full flex flex-col">
    <!-- Phase: NEXT_UP -->
    <div v-if="phase === 'rest'" class="flex flex-col items-center justify-center h-full px-6 text-center">
      <p class="text-white/50 text-sm mb-2">Next up</p>
      <h2 class="text-2xl font-bold text-white mb-6">{{ nextExerciseName }}</h2>
      <div class="relative w-48 h-48 mb-6">
        <svg class="w-full h-full -rotate-90" viewBox="0 0 100 100">
          <circle cx="50" cy="50" r="42" fill="none" stroke="#ffffff10" stroke-width="6"/>
          <circle cx="50" cy="50" r="42" fill="none" stroke="#4cb782" stroke-width="6"
            :stroke-dasharray="264" :stroke-dashoffset="restProgress * 264"
            stroke-linecap="round" class="transition-all duration-300 ease-linear"/>
        </svg>
        <div class="absolute inset-0 flex items-center justify-center">
          <span class="text-5xl font-bold text-[#4cb782]">{{ restCountdown }}</span>
        </div>
      </div>
      <p class="text-white/30 text-sm">Get ready...</p>
    </div>

    <!-- Phase: EXERCISE -->
    <div v-else-if="phase === 'exercise'" class="flex flex-col items-center justify-center h-full px-6 text-center">
      <p class="text-white/50 text-sm mb-2">Exercise {{ currentIndex + 1 }} of {{ totalExercises }}</p>
      <h2 class="text-2xl font-bold text-white mb-6">{{ currentExerciseName }}</h2>
      <div class="relative w-48 h-48 mb-6">
        <svg class="w-full h-full -rotate-90" viewBox="0 0 100 100">
          <circle cx="50" cy="50" r="42" fill="none" stroke="#ffffff10" stroke-width="6"/>
          <circle cx="50" cy="50" r="42" fill="none" stroke="#f97316" stroke-width="6"
            :stroke-dasharray="264" :stroke-dashoffset="(1 - timerProgress) * 264"
            stroke-linecap="round" class="transition-all duration-300 ease-linear"/>
        </svg>
        <div class="absolute inset-0 flex items-center justify-center">
          <span class="text-5xl font-bold text-white">{{ displayTime }}</span>
        </div>
      </div>
      <div class="w-full max-w-xs bg-white/10 rounded-full h-1.5 mb-4">
        <div class="bg-[#f97316] h-full rounded-full transition-all duration-300 ease-linear"
          :style="{ width: `${timerProgress * 100}%` }"></div>
      </div>
      <p class="text-white/30 text-sm">Go!</p>
    </div>

    <!-- Phase: FINISHED -->
    <div v-else class="flex flex-col items-center justify-center h-full px-6 text-center">
      <div class="w-20 h-20 bg-[#4cb782]/20 rounded-full flex items-center justify-center mb-6">
        <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="#4cb782" stroke-width="2.5"><path d="M20 6 9 17l-5-5"/></svg>
      </div>
      <h2 class="text-2xl font-bold text-white mb-2">Workout Complete!</h2>
      <p class="text-white/50 text-sm mb-6">{{ currentWorkoutName }}</p>

      <div class="grid grid-cols-3 gap-4 mb-8 w-full max-w-xs">
        <div class="bg-[#181825] rounded-xl p-3">
          <p class="text-2xl font-bold text-white">{{ Math.floor(totalDuration / 60) }}m</p>
          <p class="text-xs text-white/40">Duration</p>
        </div>
        <div class="bg-[#181825] rounded-xl p-3">
          <p class="text-2xl font-bold text-white">{{ totalExercises }}</p>
          <p class="text-xs text-white/40">Exercises</p>
        </div>
        <div class="bg-[#181825] rounded-xl p-3">
          <p class="text-2xl font-bold text-[#4cb782]">{{ Math.round(totalKcal) }}</p>
          <p class="text-xs text-white/40">Kcal</p>
        </div>
      </div>

      <button
        @click="$emit('finish')"
        class="bg-[#4cb782] text-[#1e1e2e] rounded-xl px-8 py-3 font-semibold hover:bg-[#5dd495] transition-colors"
      >
        Done
      </button>
    </div>

    <!-- Cancel (only during exercise/rest) -->
    <div v-if="phase !== 'finished'" class="absolute top-4 left-4">
      <button
        @click="cancelWorkout"
        class="text-white/40 hover:text-white/70 text-sm px-3 py-1.5"
      >
        Cancel
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, onUnmounted, nextTick } from 'vue'
import { api } from '../api'

const props = defineProps({
  workout: { type: Object, required: true },
})
const emit = defineEmits(['finish', 'cancel'])

// State
const phase = ref('rest')  // 'rest' | 'exercise' | 'finished'
const currentIndex = ref(0)
const timer = ref(0)
const restCountdown = ref(5)
const timerProgress = ref(0)
const restProgress = ref(0)
let intervalId = null
let startTime = null

// Derived
const exercises = computed(() => props.workout.exercises || [])
const totalExercises = computed(() => exercises.value.length)
const currentExercise = computed(() => exercises.value[currentIndex.value] || {})
const currentExerciseName = computed(() => currentExercise.value.exercise?.name || currentExercise.value.exercise_name || 'Exercise')
const nextExercise = computed(() => exercises.value[currentIndex.value + 1] || {})
const nextExerciseName = computed(() => nextExercise.value.exercise?.name || nextExercise.value.exercise_name || '')
const currentDuration = computed(() => currentExercise.value.duration_seconds || 30)

const totalDuration = computed(() => {
  return exercises.value.reduce((sum, e) => sum + (e.duration_seconds || 30), 0) + (Math.max(0, exercises.value.length - 1) * 5)
})

const totalKcal = computed(() => {
  return exercises.value.reduce((sum, e) => {
    const dur = e.duration_seconds || 30
    const kpm = e.exercise?.default_kcal_per_min || 5
    return sum + (dur / 60) * kpm
  }, 0)
})

const displayTime = computed(() => {
  const s = Math.ceil(timer.value)
  const m = Math.floor(s / 60)
  const sec = s % 60
  return m > 0 ? `${m}:${sec.toString().padStart(2, '0')}` : `${sec}`
})

const currentWorkoutName = computed(() => props.workout.name || 'Workout')

// Timer logic
function startExercise() {
  phase.value = 'exercise'
  timer.value = currentDuration.value
  timerProgress.value = 0
  startTime = Date.now()
  clearInterval(intervalId)
  intervalId = setInterval(() => {
    const elapsed = (Date.now() - startTime) / 1000
    const remaining = currentDuration.value - elapsed
    timer.value = Math.max(0, remaining)
    timerProgress.value = elapsed / currentDuration.value

    if (elapsed >= currentDuration.value) {
      playBeep()
      nextTick(() => {
        if (currentIndex.value >= totalExercises.value - 1) {
          finishWorkout()
        } else {
          startRest()
        }
      })
    }
  }, 50)
}

function startRest() {
  phase.value = 'rest'
  restCountdown.value = 5
  restProgress.value = 0
  const restStart = Date.now()
  clearInterval(intervalId)
  intervalId = setInterval(() => {
    const elapsed = (Date.now() - restStart) / 1000
    restCountdown.value = Math.max(0, 5 - Math.floor(elapsed))
    restProgress.value = elapsed / 5

    if (elapsed >= 5) {
      currentIndex.value++
      playBeep()
      nextTick(startExercise)
    }
  }, 50)
}

function finishWorkout() {
  clearInterval(intervalId)
  phase.value = 'finished'
  saveSession()
}

function playBeep() {
  try {
    const ctx = new (window.AudioContext || window.webkitAudioContext)()
    const osc = ctx.createOscillator()
    const gain = ctx.createGain()
    osc.connect(gain)
    gain.connect(ctx.destination)
    osc.frequency.value = 880
    osc.type = 'sine'
    gain.gain.setValueAtTime(0.3, ctx.currentTime)
    gain.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.3)
    osc.start(ctx.currentTime)
    osc.stop(ctx.currentTime + 0.3)

    // Also vibrate if available
    if (navigator.vibrate) navigator.vibrate(200)
  } catch (e) {
    // Audio context may not be available
  }
}

async function saveSession() {
  try {
    const sessionData = {
      template_id: props.workout.id,
      template_name: props.workout.name || '',
      total_duration_seconds: totalDuration.value,
      total_kcal_estimated: totalKcal.value,
      exercises: exercises.value.map((e, i) => ({
        exercise_id: e.exercise?.id || e.exercise_id,
        exercise_name: e.exercise?.name || e.exercise_name || '',
        duration_seconds: e.duration_seconds || 30,
        kcal_burned: ((e.duration_seconds || 30) / 60) * (e.exercise?.default_kcal_per_min || 5),
        order_index: i,
        completed: true,
      })),
    }
    await api.createSession(sessionData)
  } catch (e) {
    console.error('Failed to save session', e)
  }
}

function cancelWorkout() {
  clearInterval(intervalId)
  emit('cancel')
}

onMounted(() => {
  // Start with rest screen, then auto-begin after 5s
  startRest()
})

onUnmounted(() => {
  clearInterval(intervalId)
})
</script>

// frontend/src/components/WorkoutRunner.tsx
import { useEffect, useMemo, useRef, useState } from "react";
import { api, type WorkoutTemplate } from "../api";
import ExerciseImage from "./ExerciseImage";

type Phase = "rest" | "exercise" | "roundrest" | "finished";

const REST_SECONDS = 5;
const DEFAULT_KCAL_PER_MIN = 5;
const RING = 264; // 2πr, r=42

function kcalFor(durationSeconds: number, kcalPerMin: number): number {
  return (durationSeconds / 60) * kcalPerMin;
}

function beep(): void {
  try {
    const Ctor = window.AudioContext || window.webkitAudioContext;
    if (!Ctor) return;
    const ctx = new Ctor();
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();
    osc.connect(gain);
    gain.connect(ctx.destination);
    osc.frequency.value = 880;
    osc.type = "sine";
    gain.gain.setValueAtTime(0.3, ctx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.3);
    osc.start(ctx.currentTime);
    osc.stop(ctx.currentTime + 0.3);
    if (navigator.vibrate) navigator.vibrate(200);
  } catch {
    // AudioContext may be unavailable (autoplay policy / SSR); ignore.
  }
}

interface WorkoutRunnerProps {
  workout: WorkoutTemplate;
  onFinish: () => void;
  onCancel: () => void;
}

export default function WorkoutRunner({
  workout,
  onFinish,
  onCancel,
}: WorkoutRunnerProps) {
  const exercises = workout.exercises;
  const totalExercises = exercises.length;
  const rounds = Math.max(1, workout.rounds || 1);
  const restBetween = Math.max(0, workout.rest_between_rounds || 0);

  const [phase, setPhase] = useState<Phase>("rest");
  const [currentIndex, setCurrentIndex] = useState(0);
  const [currentRound, setCurrentRound] = useState(0);
  const [timer, setTimer] = useState(0);
  const [timerProgress, setTimerProgress] = useState(0);
  const [restCountdown, setRestCountdown] = useState(REST_SECONDS);
  const [restProgress, setRestProgress] = useState(0);
  // Set during each exercise; the Skip button jumps to the next exercise/round.
  const advanceRef = useRef<() => void>(() => {});

  // Work = exercise time × rounds. Rest = configured between-round rest ×
  // (rounds − 1). Total = work + rest — matches the backend breakdown.
  const workDuration = useMemo(
    () =>
      exercises.reduce((sum, e) => sum + (e.duration_seconds || 30), 0) * rounds,
    [exercises, rounds],
  );
  const restDuration = Math.max(0, rounds - 1) * restBetween;
  const totalDuration = workDuration + restDuration;

  const totalKcal = useMemo(
    () =>
      exercises.reduce(
        (sum, e) =>
          sum +
          kcalFor(
            e.duration_seconds || 30,
            e.exercise?.default_kcal_per_min ?? DEFAULT_KCAL_PER_MIN,
          ),
        0,
      ) * rounds,
    [exercises, rounds],
  );

  // Timed state machine. Runs once on mount; the interval closes over local
  // timestamps and stable props only, so there is no stale-state hazard.
  useEffect(() => {
    let intervalId: ReturnType<typeof setInterval> | undefined;
    const clear = () => {
      if (intervalId !== undefined) {
        clearInterval(intervalId);
        intervalId = undefined;
      }
    };

    // rest(round, i) precedes exercise(round, i) for every exercise in every
    // round, so nothing is skipped.
    function startRest(round: number, i: number) {
      setPhase("rest");
      setCurrentRound(round);
      setCurrentIndex(i);
      setRestCountdown(REST_SECONDS);
      setRestProgress(0);
      const restStart = Date.now();
      clear();
      intervalId = setInterval(() => {
        const elapsed = (Date.now() - restStart) / 1000;
        setRestCountdown(Math.max(0, REST_SECONDS - Math.floor(elapsed)));
        setRestProgress(Math.min(1, elapsed / REST_SECONDS));
        if (elapsed >= REST_SECONDS) {
          clear();
          beep();
          startExercise(round, i);
        }
      }, 50);
    }

    function advanceFrom(round: number, i: number) {
      clear();
      beep();
      if (i < totalExercises - 1) startRest(round, i + 1);
      else if (round < rounds - 1) startRoundRest(round + 1);
      else finish();
    }

    // Configurable rest between rounds. Replaces the short get-ready before the
    // first exercise of the next round.
    function startRoundRest(nextRound: number) {
      if (restBetween <= 0) {
        startExercise(nextRound, 0);
        return;
      }
      setPhase("roundrest");
      setCurrentRound(nextRound);
      setCurrentIndex(0);
      setRestCountdown(restBetween);
      setRestProgress(0);
      const restStart = Date.now();
      clear();
      advanceRef.current = () => {
        clear();
        beep();
        startExercise(nextRound, 0);
      };
      intervalId = setInterval(() => {
        const elapsed = (Date.now() - restStart) / 1000;
        setRestCountdown(Math.max(0, Math.ceil(restBetween - elapsed)));
        setRestProgress(Math.min(1, elapsed / restBetween));
        if (elapsed >= restBetween) {
          clear();
          beep();
          startExercise(nextRound, 0);
        }
      }, 50);
    }

    function startExercise(round: number, i: number) {
      setPhase("exercise");
      setCurrentRound(round);
      setCurrentIndex(i);
      const dur = exercises[i]?.duration_seconds || 30;
      setTimer(dur);
      setTimerProgress(0);
      const start = Date.now();
      clear();
      advanceRef.current = () => advanceFrom(round, i);
      intervalId = setInterval(() => {
        const elapsed = (Date.now() - start) / 1000;
        setTimer(Math.max(0, dur - elapsed));
        setTimerProgress(Math.min(1, elapsed / dur));
        if (elapsed >= dur) advanceFrom(round, i);
      }, 50);
    }

    function finish() {
      clear();
      setPhase("finished");
      void saveSession();
    }

    async function saveSession() {
      try {
        await api.createSession({
          template_id: workout.id,
          template_name: workout.name || "",
          total_duration_seconds: totalDuration,
          total_kcal_estimated: totalKcal,
          exercises: exercises.map((e, i) => ({
            exercise_id: e.exercise?.id ?? e.exercise_id,
            exercise_name: e.exercise?.name || "",
            duration_seconds: e.duration_seconds || 30,
            kcal_burned: kcalFor(
              e.duration_seconds || 30,
              e.exercise?.default_kcal_per_min ?? DEFAULT_KCAL_PER_MIN,
            ),
            order_index: i,
            completed: true,
          })),
        });
      } catch (err) {
        console.error("Failed to save session", err);
      }
    }

    if (totalExercises === 0) {
      finish();
    } else {
      startRest(0, 0);
    }

    return clear;
  }, [exercises, totalExercises, rounds, restBetween, totalDuration, totalKcal, workout.id, workout.name]);

  const currentName = exercises[currentIndex]?.exercise?.name ?? "Exercise";
  const currentImage = exercises[currentIndex]?.exercise?.image_url ?? null;
  const displayTime = (() => {
    const s = Math.ceil(timer);
    const m = Math.floor(s / 60);
    const sec = s % 60;
    return m > 0 ? `${m}:${String(sec).padStart(2, "0")}` : `${sec}`;
  })();
  const restClock = (() => {
    const s = Math.max(0, restCountdown);
    const m = Math.floor(s / 60);
    const sec = s % 60;
    return `${m}:${String(sec).padStart(2, "0")}`;
  })();

  return (
    <div className="workout-runner bg-bg h-full flex flex-col no-select">
      {phase === "rest" && (
        <div className="flex flex-col items-center justify-center h-full px-6 text-center">
          <p className="text-fg/50 text-sm mb-2">Next up</p>
          <h2 className="text-2xl font-bold text-fg mb-6">{currentName}</h2>
          <ExerciseImage
            src={currentImage}
            alt={currentName}
            iconSize={48}
            className="w-56 h-40 rounded-2xl mb-6 border border-fg/10"
          />
          <div className="relative w-48 h-48 mb-6">
            <svg className="w-full h-full -rotate-90" viewBox="0 0 100 100">
              <circle cx="50" cy="50" r="42" fill="none" stroke="var(--track)" strokeWidth="6" />
              <circle
                cx="50"
                cy="50"
                r="42"
                fill="none"
                stroke="var(--accent)"
                strokeWidth="6"
                strokeDasharray={RING}
                strokeDashoffset={restProgress * RING}
                strokeLinecap="round"
                className="transition-all duration-300 ease-linear"
              />
            </svg>
            <div className="absolute inset-0 flex items-center justify-center">
              <span className="text-5xl font-bold text-accent">{restCountdown}</span>
            </div>
          </div>
          <p className="text-fg/30 text-sm">Get ready...</p>
        </div>
      )}

      {phase === "roundrest" && (
        <div className="flex flex-col items-center justify-center h-full px-6 text-center">
          <p className="text-fg/50 text-sm mb-2">Round rest</p>
          <h2 className="text-2xl font-bold text-fg mb-6">
            Round {currentRound + 1}/{rounds} next
          </h2>
          <div className="relative w-48 h-48 mb-6">
            <svg className="w-full h-full -rotate-90" viewBox="0 0 100 100">
              <circle cx="50" cy="50" r="42" fill="none" stroke="var(--track)" strokeWidth="6" />
              <circle
                cx="50"
                cy="50"
                r="42"
                fill="none"
                stroke="var(--accent)"
                strokeWidth="6"
                strokeDasharray={RING}
                strokeDashoffset={restProgress * RING}
                strokeLinecap="round"
                className="transition-all duration-300 ease-linear"
              />
            </svg>
            <div className="absolute inset-0 flex items-center justify-center">
              <span className="text-4xl font-bold text-accent">{restClock}</span>
            </div>
          </div>
          <p className="text-fg/30 text-sm mb-4">Catch your breath</p>
          <button
            onClick={() => advanceRef.current()}
            className="text-sm text-fg/50 hover:text-fg border border-fg/15 rounded-xl px-5 py-2 transition-colors"
          >
            Skip rest
          </button>
        </div>
      )}

      {phase === "exercise" && (
        <div className="flex flex-col items-center justify-center h-full px-6 text-center">
          <p className="text-fg/50 text-sm mb-2">
            Exercise {currentIndex + 1} of {totalExercises}
            {rounds > 1 && (
              <span className="text-accent"> &middot; Round {currentRound + 1}/{rounds}</span>
            )}
          </p>
          <h2 className="text-2xl font-bold text-fg mb-6">{currentName}</h2>
          <ExerciseImage
            src={currentImage}
            alt={currentName}
            iconSize={48}
            className="w-56 h-40 rounded-2xl mb-6 border border-fg/10"
          />
          <div className="relative w-48 h-48 mb-6">
            <svg className="w-full h-full -rotate-90" viewBox="0 0 100 100">
              <circle cx="50" cy="50" r="42" fill="none" stroke="var(--track)" strokeWidth="6" />
              <circle
                cx="50"
                cy="50"
                r="42"
                fill="none"
                stroke="var(--timer)"
                strokeWidth="6"
                strokeDasharray={RING}
                strokeDashoffset={(1 - timerProgress) * RING}
                strokeLinecap="round"
                className="transition-all duration-300 ease-linear"
              />
            </svg>
            <div className="absolute inset-0 flex items-center justify-center">
              <span className="text-5xl font-bold text-fg">{displayTime}</span>
            </div>
          </div>
          <p className="text-fg/30 text-sm">Go!</p>
          <button
            onClick={() => advanceRef.current()}
            className="mt-4 text-sm text-fg/50 hover:text-fg border border-fg/15 rounded-xl px-5 py-2 transition-colors"
          >
            Skip
          </button>
        </div>
      )}

      {phase === "finished" && (
        <div className="flex flex-col items-center justify-center h-full px-6 text-center">
          <div className="w-20 h-20 bg-accent/20 rounded-full flex items-center justify-center mb-6">
            <svg width="36" height="36" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" strokeWidth="2.5">
              <path d="M20 6 9 17l-5-5" />
            </svg>
          </div>
          <h2 className="text-2xl font-bold text-fg mb-2">Workout Complete!</h2>
          <p className="text-fg/50 text-sm mb-6">{workout.name || "Workout"}</p>

          <div className="grid grid-cols-3 gap-4 mb-8 w-full max-w-xs">
            <div className="bg-surface rounded-xl p-3">
              <p className="text-2xl font-bold text-fg">{Math.floor(totalDuration / 60)}m</p>
              <p className="text-xs text-fg/40">Duration</p>
            </div>
            <div className="bg-surface rounded-xl p-3">
              <p className="text-2xl font-bold text-fg">{totalExercises}</p>
              <p className="text-xs text-fg/40">Exercises</p>
            </div>
            <div className="bg-surface rounded-xl p-3">
              <p className="text-2xl font-bold text-accent">{Math.round(totalKcal)}</p>
              <p className="text-xs text-fg/40">Kcal</p>
            </div>
          </div>

          <button
            onClick={onFinish}
            className="bg-accent text-on-accent rounded-xl px-8 py-3 font-semibold hover:bg-accent-hover transition-colors"
          >
            Done
          </button>
        </div>
      )}

      {phase !== "finished" && (
        <div className="absolute top-4 left-4">
          <button
            onClick={onCancel}
            className="text-fg/40 hover:text-fg/70 text-sm px-3 py-1.5"
          >
            Cancel
          </button>
        </div>
      )}
    </div>
  );
}
